<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Zado-1" name="TestNGClass" tests="1" failures="0" timestamp="27 Jan 2017 06:22:04 GMT" time="43.530" errors="1">
  <testcase name="launchapp" time="43.530" classname="TestNGClass">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at zautomate.zadoqa.commands.Manipulation.condtionMatch(Manipulation.java:494)
	at zautomate.zadoqa.util.CommandUtils.executeAction(CommandUtils.java:451)
	at zautomate.zadoqa.datadriver.TestCaseRunner.exectuteTestCase(TestCaseRunner.java:70)
	at TestNGClass.launchapp(TestNGClass.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- launchapp -->
</testsuite> <!-- TestNGClass -->
